import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const lineFontTh = localFont({
  src: [
    {
      path: "../lib/fonts/line-seed/LINESeedSansTH_W_Th.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../lib/fonts/line-seed/LINESeedSansTH_W_Rg.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../lib/fonts/line-seed/LINESeedSansTH_W_Bd.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--line-font-th",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${lineFontTh.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col max-w-[1440px] mx-auto"
      >
        {children}
      </body>
    </html>
  );
}
